-- =============================================================================
-- Kriptobioze · Modelagem Estratigráfica de Fósseis e Camadas
-- 01_schema.sql  ·  DDL — Criação das tabelas (PostgreSQL)
--
-- Entidades modeladas (ver DER.md):
--   CAMADA (ID, nome_era, profundidade_media, tipo_rocha, ...)
--   FOSSIL (ID, nome_cientifico, taxonomia, idade_estimada, fk_camada, ...)
--
-- Relacionamento: 1 CAMADA (N) --- (1) FOSSIL  (FK fk_camada -> camada.id)
-- Este script mantém o mesmo schema que o JPA/Hibernate gera para as
-- entidades com.kriptobioze.model.Camada e com.kriptobioze.model.Fossil.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabela CAMADA
-- Representa uma camada (estrato) geológico. A profundidade_media indica o
-- quanto abaixo da superfície o estrato se encontra: como Darwin postulou,
-- quanto maior a profundidade, mais antiga a camada costuma ser.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS camada (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- PK
    nome_era            VARCHAR(100)   NOT NULL,
    profundidade_media  DOUBLE PRECISION NOT NULL,
    tipo_rocha          VARCHAR(100)   NOT NULL,
    idade_estimada_ma   INTEGER        NOT NULL,   -- idade estimada em milhões de anos
    descricao           TEXT
);

-- -----------------------------------------------------------------------------
-- Tabela FOSSIL
-- Cada fóssil pertence obrigatoriamente a uma camada (FK fk_camada).
-- idade_estimada é a idade estimada do organismo em milhões de anos (Ma).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fossil (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- PK
    nome_cientifico       VARCHAR(150)    NOT NULL,
    taxonomia             VARCHAR(100)    NOT NULL,
    idade_estimada        DOUBLE PRECISION NOT NULL,
    fk_camada             BIGINT          NOT NULL,
    localidade_descoberta VARCHAR(200),
    descricao             TEXT,
    CONSTRAINT fk_fossil_camada
        FOREIGN KEY (fk_camada) REFERENCES camada (id)   -- FK
);

-- Índice para acelerar os INNER JOIN entre fossil e camada (numeração da fk)
CREATE INDEX IF NOT EXISTS idx_fossil_fk_camada ON fossil (fk_camada);